# Generated by Django 4.0.5 on 2022-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_sensor_measurements_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
